 
let labNames = [
    {text: "numbers", clicked: false}, 
    {text: "Data Types", clicked: false}, 
    {text: "strings", clicked: false}, 
    {text: "boolean", clicked: false}, 
    {text: "null", clicked: false} ,
    {text: "undefined", clicked: false}, 
    {text: "NaN", clicked: false}, 
    {text: "immutability", clicked: false}, 
    {text: "conditionals", clicked: false}, 
    {text: "loops", clicked: false}, 
    {text: "algorithms", clicked: false}, 
    {text: "Git", clicked: false}, 
    {text: "CSS", clicked: false}, 
    {text: "HTML", clicked: false}, 
    {text: "Javascript", clicked: false}, 
    {text: "functions and arrays", clicked: false}, 
    {text: "Arrays", clicked: false}, 
    {text: "Objects", clicked: false}, 
    {text: "transitions & animations", clicked: false}, 
    {text: "FlexBox", clicked: false}, 
    {text: "clone", clicked: false}, 
    {text: "Responsive Design", clicked: false}, 
    {text: "Map", clicked: false}, 
    {text: "Reduce", clicked: false}, 
    {text: "Filter", clicked: false}, 
    {text: "Sort", clicked: false}, 
    {text: "Selectors", clicked: false}, 
    {text: "Manipulation", clicked: false}, 
    {text: "DOM", clicked: false}, 
    {text: "Lab", clicked: false}, 
    {text: "hoisting", clicked: false}, 
    {text: "shadowing", clicked: false}, 
    {text: "OOP", clicked: false}, 
    {text: "classes", clicked: false}, 
    {text: "methods", clicked: false}, 
    {text: "JS Hint", clicked: false}, 
    {text: "invocation", clicked: false}, 
    {text: "Bootstrap", clicked: false}, 
    {text: "Callbacks", clicked: false}, 
    {text: "functions", clicked: false}, 
    {text: "command line", clicked: false}, 
    {text: "Grids", clicked: false}, 
    {text: "Jasmine", clicked: false}, 
    {text: "2D arrays", clicked: false}, 
    {text: "abstraction", clicked: false}, 
    {text: "accessibility", clicked: false}, 
    {text: "binary", clicked: false}, 
    {text: "inline", clicked: false}, 
    {text: "blockline", clicked: false}, 
    {text: "bugs", clicked: false}, 
    {text: "command", clicked: false}, 
    {text: "debugging", clicked: false}, 
    {text: "event", clicked: false}, 
    {text: "for loop", clicked: false}, 
    {text: "function", clicked: false}, 
    {text: "if-statement", clicked: false}, 
    {text: "while loop", clicked: false}, 
    {text: "iteration", clicked: false}, 
    {text: "variable", clicked: false}, 
    {text: "API", clicked: false}, 
    {text: "concatenation", clicked: false}, 
    {text: "constant", clicked: false}, 
    {text: "data structures", clicked: false}, 
    {text: "prod", clicked: false}, 
    {text: "framework", clicked: false}, 
    {text: "full stack", clicked: false}, 
    {text: "git hub", clicked: false}, 
    {text: "JSON", clicked: false}, 
    {text: "JQuery", clicked: false}, 
    {text: "logical operators", clicked: false}, 
    {text: "nested", clicked: false}, 
    {text: "node.js", clicked: false}, 
    {text: "recursion", clicked: false}, 
    {text: "Front end", clicked: false}, 
    {text: "Back end", clicked: false}, 
    {text: "HTML attribute", clicked: false}, 
    {text: "404", clicked: false}, 
    {text: "Browser", clicked: false}, 
    {text: "cache", clicked: false}, 



];
